// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apovygnmtwdcyjosdnxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwb3Z5Z25tdHdkY3lqb3NkbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzUxMzUsImV4cCI6MjA2NzA1MTEzNX0.50n5QcB6WYhq2NLNdVHKbuFHc7mann6N_YYNbpdOG6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});